# Generated by Django 3.2 on 2021-12-19 21:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.FloatField()),
                ('px', models.FloatField()),
                ('type', models.CharField(choices=[('BD', 'Bid'), ('AK', 'Ask')], max_length=2)),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.ticker')),
            ],
        ),
    ]
