# Generated by Django 3.2 on 2021-12-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.FloatField()),
                ('px', models.FloatField()),
                ('type', models.CharField(choices=[('BD', 'Bid'), ('AK', 'Ask')], max_length=2)),
            ],
        ),
    ]
